TesteNET/TesteNET/Controllers/CategoriaController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TesteNET.Models;

namespace TesteNET.Controllers
{
    public class CategoriaController : Controller
    {
        private FitCardDataModel db = new FitCardDataModel();
        private string mensagemController = "MensagemRetorno";

        // GET: Categoria
        public ActionResult Index(int? p)
        {
            //var estabelecimentoes = db.Estabelecimentoes.Include(e => e.Categoria).Include(e => e.Estado);
            //return View(estabelecimentoes.ToList());

            var categorias = from e in db.Categorias
                                       orderby e.Nome ascending
                                       select e;

            //Definição de itens por página e pagina atual
            int itensPagina = 10;
            int numeroPagina = (p ?? 1);

            // Retorna lista para a view
            return View(categorias.ToPagedList(numeroPagina, itensPagina));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="ativo"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ativo(string id, string ativo)
        {
            // Verifica se foi enviado o ID
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            int ID = Convert.ToInt32(id);

            Categoria categoria = db.Categorias.Find(ID);
            bool statusAtivo = Convert.ToBoolean(ativo);

            categoria.Status = statusAtivo;

            db.Entry(categoria).CurrentValues.SetValues(categoria);
            db.SaveChanges();

            return new EmptyResult();
        }

        // GET: Categoria/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // GET: Categoria/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categoria/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                categoria.Status = true;
                db.Categorias.Add(categoria);
                db.SaveChanges();

                TempData.Add(mensagemController, string.Format("A categoria \"{0}\" foi incluída com sucesso!", categoria.Nome));
                TempData.Add("MensagemTipo", "success");

                return RedirectToAction("Index");
            }

            return View(categoria);
        }

        // GET: Categoria/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // POST: Categoria/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoria).State = EntityState.Modified;
                db.SaveChanges();

                TempData.Add(mensagemController, string.Format("Os dados da categoria \"{0}\" foram atualizados com sucesso!", categoria.Nome));
                TempData.Add("MensagemTipo", "success");

                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        // GET: Categoria/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // POST: Categoria/Delete/5
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            // Verifica se foi enviado o ID
            if (String.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            int ID = Convert.ToInt32(id);

            Categoria categoria = db.Categorias.Find(ID);
            db.Categorias.Remove(categoria);
            db.SaveChanges();

            return new EmptyResult();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TesteNET/TesteNET/Controllers/EstabelecimentoController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TesteNET.Models;

namespace TesteNET.Controllers
{
    public class EstabelecimentoController : Controller
    {
        private FitCardDataModel db = new FitCardDataModel();
        private string mensagemController = "MensagemRetorno";

        // GET: Estabelecimento
        public ActionResult Index(int? p)
        {
            //var estabelecimentoes = db.Estabelecimentoes.Include(e => e.Categoria).Include(e => e.Estado);
            //return View(estabelecimentoes.ToList());

            var listaEstabelecimento = from e in db.Estabelecimentos
                                       orderby e.RazaoSocial ascending
                                       select e;

            //Definição de itens por página e pagina atual
            int itensPagina = 10;
            int numeroPagina = (p ?? 1);

            // Retorna lista para a view
            return View(listaEstabelecimento.ToPagedList(numeroPagina, itensPagina));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="ativo"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ativo(string id, string ativo)
        {
            // Verifica se foi enviado o ID
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            int ID = Convert.ToInt32(id);

            Estabelecimento estabelecimento = db.Estabelecimentos.Find(ID);
            bool statusAtivo = Convert.ToBoolean(ativo);

            estabelecimento.Status = statusAtivo;

            db.Entry(estabelecimento).CurrentValues.SetValues(estabelecimento);
            db.SaveChanges();

            return new EmptyResult();
        }

        // GET: Estabelecimento/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estabelecimento estabelecimento = db.Estabelecimentos.Find(id);
            if (estabelecimento == null)
            {
                return HttpNotFound();
            }
            return View(estabelecimento);
        }

        // GET: Estabelecimento/Create
        public ActionResult Create()
        {
            ViewBag.IDCategoria = new SelectList(db.Categorias, "IDCategoria", "Nome");
            // Carrega ViewBag com lista de estados e cidades
            ViewBag.IDEstado = new SelectList(db.Estados.OrderBy(o => o.nome), "IDEstado", "nome");
            ViewBag.IDCidade = new SelectList(db.Cidades.Where(w => w.IDCidade == 0).OrderBy(o => o.nome), "IDCidade", "nome");
            return View();
        }

        // POST: Estabelecimento/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Estabelecimento estabelecimento)
        {
            if (ModelState.IsValid)
            {
                estabelecimento.DataCadastro = DateTime.Now;
                estabelecimento.Status = true;
                db.Estabelecimentos.Add(estabelecimento);
                db.SaveChanges();

                TempData.Add(mensagemController, string.Format("O estabelecimento \"{0}\" foi incluído com sucesso!", estabelecimento.NomeFantasia));
                TempData.Add("MensagemTipo", "success");

                return RedirectToAction("Index");
            }

            ViewBag.IDCategoria = new SelectList(db.Categorias, "IDCategoria", "Nome", estabelecimento.IDCategoria);
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "nome", estabelecimento.IDCidade);
            ViewBag.IDEstado = new SelectList(db.Estados, "IDEstado", "nome", estabelecimento.IDEstado);

            return View(estabelecimento);
        }

        // GET: Estabelecimento/Edit/5
        public ActionResult Edit(string id)
        {
            // Verifica se foi enviado o ID
            if (string.IsNullOrEmpty(id))
            {
                TempData.Add(mensagemController, "Não foi possível acessar o formulário de edição: nenhuma estabelecimento informado para consulta");
                TempData.Add("MensagemTipo", "warning");

                return RedirectToAction("Index");
            }

            int ID = Convert.ToInt32(id);

            Estabelecimento estabelecimento = db.Estabelecimentos.Find(ID);
            if (estabelecimento == null)
            {
                TempData.Add(mensagemController, "Não foi possível acessar o formulário de edição: nenhum estabelecimento foi encontrado");
                TempData.Add("MensagemTipo", "warning");

                return RedirectToAction("Index");
            }

            int IDEstado = (estabelecimento.IDCidade > 0) ? db.Cidades.Find(estabelecimento.IDCidade).IDEstado : 0;
            ViewBag.IDEstado = new SelectList(db.Estados.OrderBy(o => o.uf), "IDEstado", "Nome", IDEstado);
            ViewBag.IDCidade = new SelectList(db.Cidades.Where(w => w.IDEstado == IDEstado).OrderBy(o => o.nome), "IDCidade", "Nome", estabelecimento.IDCidade);

            ViewBag.IDCategoria = new SelectList(db.Categorias, "IDCategoria", "Nome", estabelecimento.IDCategoria);
            //ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "nome", estabelecimento.IDCidade);
            //ViewBag.IDEstado = new SelectList(db.Estados, "IDEstado", "nome", estabelecimento.IDEstado);
            return View(estabelecimento);
        }

        // POST: Estabelecimento/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDEstabelecimento,IDCategoria,RazaoSocial,NomeFantasia,CNPJ,Email,Endereco,IDEstado,IDCidade,Telefone,DataCadastro,Status")] Estabelecimento estabelecimento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estabelecimento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDCategoria = new SelectList(db.Categorias, "IDCategoria", "Nome", estabelecimento.IDCategoria);
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "nome", estabelecimento.IDCidade);
            ViewBag.IDEstado = new SelectList(db.Estados, "IDEstado", "nome", estabelecimento.IDEstado);
            return View(estabelecimento);
        }

        // GET: Estabelecimento/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estabelecimento estabelecimento = db.Estabelecimentos.Find(id);
            if (estabelecimento == null)
            {
                return HttpNotFound();
            }
            return View(estabelecimento);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            // Verifica se foi enviado o ID
            if (String.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Descriptografa o ID do usuário
            int ID = Convert.ToInt32(id);

            Estabelecimento estabelecimento = db.Estabelecimentos.Find(id);
            db.Estabelecimentos.Remove(estabelecimento);
            db.SaveChanges();

            return new EmptyResult();
        }

        /// <summary>
        /// Recupera as cidades de um determinado estado
        /// </summary>
        /// <param name="IDEstado">int IDEstado</param>
        /// <returns>
        /// Lista JSON com as cidades de um determinado estado
        /// </returns>
        [HttpPost]
        public ActionResult SelecionarCidadesPorEstado(int? IDEstado)
        {
            // Verifica se foi enviado o ID do estado   
            if (IDEstado == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Realiza um SELECT na tabela "cidade" para listar as cidades de um determinado estado
            var cidades = from c in db.Cidades
                          where c.IDEstado == IDEstado
                          orderby c.nome
                          select new cidadelista() { IDCidade = c.IDCidade, Nome = c.nome };

            // Retorna um JSON com o resultado do SELECT
            return Json(cidades, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TesteNET/TesteNET/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TesteNET/TesteNET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FitCard Teste</title>
    @Styles.Render("~/Content/css")
    <!-- Custom styles for this template -->
    <link href="~/Content/style.css?v=@Guid.NewGuid()" rel="stylesheet">
    <link href="~/Content/style-responsive.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="mega-nav">
    <section id="container" class="">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("FitCard", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                        <li class="dropdown">
                            <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#">
                                <i class="fa fa-building"></i> Estabelecimentos <b class="fa fa-angle-down"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index","Estabelecimento")">Lista</a></li>
                                <li><a href="@Url.Action("Index","Categoria")">Categorias</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <section id="main-content">
            <section class="wrapper">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Teste FitCard</p>
                </footer>
            </section>
        </section>
    </section>
    <div class="loading-screen">
        <div class="vertical-center">
            <span style="font-size:40px;margin-right:10px;color:#FFF;">FITCARD</span>
            <i class="fa fa-spinner fa-pulse fa-4x text-white"></i>
        </div>
    </div>
    
    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts")

    <!--common script for all pages-->
    <script src="~/Scripts/common-scripts.js?v=@Guid.NewGuid()" id="customScript" data-path=""></script>

    @RenderSection("scripts", required: false)
</body>
</html>